name: Tinify Images

on:
  push:
    branches: [ main, master ]

jobs:
  tinify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tinify/tinify-github-action@v1
        with:
          api_key: ${{ secrets.TINYPNG_KEY }}
